<?

//include only that one, rest required files will be included from it
include "Nathejk/phpqrcode/qrlib.php";

//write code into file, Error corection lecer is lowest, L (one form: L,M,Q,H)
//each code square will be 4x4 pixels (4x zoom)
//code will have 2 code squares white boundary around 

//QRcode::png('PHP QR Code :)', 'test.png', 'L', 4, 2);

//same as above but outputs file directly into browser (with appr. header etc.)
//all other settings are default
//WARNING! it should be FIRST and ONLY output generated by script, otherwise
//rest of output will land inside PNG binary, breaking it for sure
$nummer = isset($_GET['patrulje']) ? intval($_GET['patrulje']) : 0;
QRcode::png('http://tilmelding.nathejk.dk/qr.php?n=' . $nummer);

